node-identifier: "hub1" # this needs to be a unique identifier for this node
hub: true # is this node a hub?

non-hub-nodes: # these are the proxy names of all the non hub servers/nodes
  - "factions1"
  - "game-server"

poll-interval: 5000 # milliseconds
position-interval: 5000 # milliseconds
bypass-permission: "queue.bypass"

priorities:
  VIP:
    permission: "queue.vip"
    priority: 100
  MVP:
    permission: "queue.mvp"
    priority: 500