poll-interval: 5000 # milliseconds
position-interval: 5000 # milliseconds
bypass-permission: "queue.bypass"

hubs:
  - "hub"

priorities:
  VIP:
    permission: "queue.vip"
    priority: 100
  MVP:
    permission: "queue.mvp"
    priority: 500